#  Artificial Neural Network

## Problem Statement 

  Customers of a certain bank are leaving the bank.

 As a data scientist you have to identify which customers are at high risk of leaving the bank.

### Importing the libraries

In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf
tf.__version__

'2.9.1'

## Part 1 - Data Preprocessing

#### Importing the dataset

In [2]:
dataset = pd.read_csv('Churn_Modelling.csv')
dataset.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [3]:
dataset.duplicated().sum()

0

In [4]:
dataset.nunique()

RowNumber          10000
CustomerId         10000
Surname             2932
CreditScore          460
Geography              3
Gender                 2
Age                   70
Tenure                11
Balance             6382
NumOfProducts          4
HasCrCard              2
IsActiveMember         2
EstimatedSalary     9999
Exited                 2
dtype: int64

In [5]:
dataset.isnull().sum()

RowNumber          0
CustomerId         0
Surname            0
CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

In [5]:
X = dataset.iloc[:, 3:-1].values
y = dataset.iloc[:, -1].values
print(X)
print(y)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]
[1 0 1 ... 1 1 0]


#### Encoding categorical data
#### Label Encoding the "Gender" and "Geography"  column

In [6]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:,2] = le.fit_transform(X[:,2])
X[:,1] = le.fit_transform(X[:,1])
print(X)

[[619 0 0 ... 1 1 101348.88]
 [608 2 0 ... 0 1 112542.58]
 [502 0 0 ... 1 0 113931.57]
 ...
 [709 0 0 ... 0 1 42085.58]
 [772 1 1 ... 1 0 92888.52]
 [792 0 0 ... 1 0 38190.78]]


### Splitting the dataset into the Training set and Test set

In [7]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

### Feature Scaling

In [8]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

## Part 2 - Building the ANN

### Initializing the ANN

In [9]:
ann = tf.keras.models.Sequential()   #sequential-layers-input,hidden,output

### Adding the input layer and the first hidden layer

In [13]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))  #use dense class to add hidden layers
#unit=6 no of neurons you want in 1st hidden layer
#activation function relu means rectifier activation function

### Adding the second hidden layer

In [14]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### Adding the output layer

In [15]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))
#we have binary outcome so 1 neuron
#sigmoid function will give better probability
#when doing non binary classificatio i.e. more than two category use activation=softmax

# Part 3 - Training the ANN

### Compiling the ANN

In [16]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])
#optimizer=adam performs- stochastic gradient descent
#loss=binary_cressentropy- when you have binary outcome always use binary_crossentropy if non binary then category_crossentropy
#metrics=[accuracy]- most essential ideal

### Training the ANN on the Training set

In [17]:
ann.fit(X_train, y_train, batch_size = 32, epochs = 100)
#batch size=32- batch learning is more efficient instead of comparing a prediction to the real result one by one 32 is ideal
#epochs=100- neural network will train itself 100 times to improve the accuracy

Epoch 1/100
250/250 [==============================] - 1s 2ms/step - loss: 0.6358 - accuracy: 0.7314
Epoch 2/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4929 - accuracy: 0.7960
Epoch 3/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4607 - accuracy: 0.7960
Epoch 4/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4474 - accuracy: 0.7960
Epoch 5/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4404 - accuracy: 0.7960
Epoch 6/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4359 - accuracy: 0.7960
Epoch 7/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4311 - accuracy: 0.7960
Epoch 8/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4248 - accuracy: 0.7960
Epoch 9/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4161 - accuracy: 0.7960
Epoch 10/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4063 - accura

## Part 4 - Making the predictions and evaluating the model

### Predicting the result of a single observation


Use our ANN model to predict if the customer with the following informations will leave the bank: 
1. Credit Score: 600
2. Geography: France
3. Gender: Male
4. Age: 40 years old
5. Tenure: 3 years
6. Balance: 60000
7. Number of Products: 2
8. Does this customer have a credit card? Yes
9. Is this customer an Active Member: Yes
1. Estimated Salary: $ 50000

So, should we say goodbye to that customer?

Solution:


In [60]:
print(ann.predict(sc.transform([[600,0,1,40,3,60000,2,1,1,50000]])) > 0.5)

[[False]]


### Predicting another result

In [65]:
print(ann.predict(sc.transform([[502,0,0,42,8,159660,3,1,0,113931]]))>0.5)

[[ True]]


Therefore, our ANN model predicts that this customer stays in the bank!
1. Important note 1: Notice that the values of the features were all input in a double pair of square brackets. That's because the "predict" method always expects a 2D array as the format of its inputs. And putting our values into a double pair of square brackets makes the input exactly a 2D array.
2. Important note 2: Notice also that the "France" country was not input as a string in the last column but as "1, 0, 0" in the first three columns. That's because of course the predict method expects the one-hot-encoded values of the state, and as we see in the first row of the matrix of features X, "France" was encoded as "1, 0, 0". And be careful to include these values in the first three columns, because the dummy variables are always created in the first columns.

### Predicting the Test set results

In [63]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_test.reshape(len(y_test),1), y_pred.reshape(len(y_pred),1)),1))

[[0 0]
 [1 0]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


### Making the Confusion Matrix

In [57]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)*100

[[1533   62]
 [ 210  195]]


86.4

### If we use only logistic regression without using Artificial Neural Network we will get accuracy of 80%